config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /login(.:format)                     devise/sessions#new
#             user_session POST   /login(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /logout(.:format)                    devise/sessions#destroy
#        new_user_password GET    /password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /password/edit(.:format)             devise/passwords#edit
#            user_password PATCH  /password(.:format)                  devise/passwords#update
#                          PUT    /password(.:format)                  devise/passwords#update
#                          POST   /password(.:format)                  devise/passwords#create
# cancel_user_registration GET    /cancel(.:format)                    devise/registrations#cancel
#    new_user_registration GET    /register(.:format)                  devise/registrations#new
#   edit_user_registration GET    /edit(.:format)                      devise/registrations#edit
#        user_registration PATCH  /                                    devise/registrations#update
#                          PUT    /                                    devise/registrations#update
#                          DELETE /                                    devise/registrations#destroy
#                          POST   /                                    devise/registrations#create
#                 articles GET    /articles(.:format)                  articles#index
#                  article GET    /articles/:id(.:format)              articles#show
#     delete_admin_article GET    /admin/articles/:id/delete(.:format) admin/articles#delete
#           admin_articles POST   /admin/articles(.:format)            admin/articles#create
#        new_admin_article GET    /admin/articles/new(.:format)        admin/articles#new
#       edit_admin_article GET    /admin/articles/:id/edit(.:format)   admin/articles#edit
#            admin_article GET    /admin/articles/:id(.:format)        admin/articles#show
#                          PATCH  /admin/articles/:id(.:format)        admin/articles#update
#                          PUT    /admin/articles/:id(.:format)        admin/articles#update
#                          DELETE /admin/articles/:id(.:format)        admin/articles#destroy
#                dashboard GET    /dashboard(.:format)                 admin/articles#index
#                     root GET    /                                    articles#index
# 

Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :articles, only: [:index, :show]

  namespace :admin do
    resources :articles, except: [:index] do
      get :delete, on: :member
    end
  end
  get 'dashboard', to: 'admin/articles#index', as: :dashboard

  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id           :integer          not null, primary key
#  category_id  :integer
#  user_id      :integer
#  title        :string(255)
#  excerpt      :string(255)
#  body         :text(65535)
#  published_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_articles_on_category_id  (category_id)
#  index_articles_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#

class Article < ApplicationRecord

  # Scopes
  default_scope { order('published_at DESC') }

  scope :draft,     -> { where(published_at: nil) }
  scope :published, -> { where.not(published_at: nil).where("published_at <= ?", Time.zone.now) }
  scope :scheduled, -> { where.not(published_at: nil).where("published_at > ?", Time.zone.now) }
  # scope :for_user,  -> (user) { where(user_id: user.id) }

  # Attr macros
  attr_accessor :status

  # AR Associations
  belongs_to :user
  belongs_to :category

  # AM Validations
  validates :title, presence: true, 
                    length: { maximum: 100 }
  validates :excerpt, presence: true,
                      length: { maximum: 255 }
  validates :body, presence: true
  validates :category_id, presence: true

  # Callbacks
  before_validation :clean_up_status

  def clean_up_status
    self.published_at = case status
                        when "Draft"
                          nil
                        when "Published"
                          Time.zone.now
                        else
                          published_at
                        end
    true
  end

  def self.archives
    Article.unscoped
          .select("YEAR(published_at) AS year, MONTHNAME(published_at) AS month, MONTH(published_at) AS month_num, COUNT(id) AS published")
          .published
          .group("year, month, month_num")
          .order("year DESC, month_num DESC")
  end

  def self.filtered (params)

    if params[:year].present? && params[:month].present?
      year = params[:year].to_i
      month = params[:month].to_i
      return where(published_at: DateTime.new(year, month, 1).beginning_of_day..DateTime.new(year, month, -1).end_of_day)
    end

    if params[:category].present?
      category_id = params[:category].to_i
      return where(category_id: category_id)
    end

    if params[:author].present?
      user_id = params[:author].to_i
      return where(user_id: user_id)
    end

    self
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < AdminController

    before_action :set_article, only: [:show, :edit, :update, :delete, :destroy]
    after_action :verify_authorized

    def index
      @articles = current_user.articles
                              .includes(:category)
                              .page(params[:page])
      authorize [:admin, @articles]
    end

    def show
    end

    def new
      @article = current_user.articles.build
      authorize [:admin, @article]
      categories_for_dropdown
    end

    def create
      @article = current_user.articles.build(article_params)
      authorize [:admin, @article]

      respond_to do |format|
        if @article.save
          format.html { redirect_to admin_article_path(@article), flash: { success: 'The article was successfully created' } }
        else
          categories_for_dropdown
          format.html { render 'new' }
        end
      end
    end

    def edit
      categories_for_dropdown
    end

    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to admin_article_path(@article), flash: { success: 'The article was successfully updated' } }
        else
          categories_for_dropdown
          format.html { render 'edit' }
        end
      end
    end

    def delete
    end

    def destroy
      @article.destroy

      respond_to do |format|
        format.html { redirect_to dashboard_path, flash: { success: "The article #{ @article.title } was successfully deleted" } }
      end
    end

    private

      def set_article
        @article = Article.find(params[:id])
        authorize [:admin, @article]
      end

      def categories_for_dropdown
        @categories = Category.select(:id, :name)
      end

      def article_params
        params.require(:article).permit(
                                        :category_id, 
                                        :title, 
                                        :excerpt, 
                                        :body,
                                        :published_at,
                                        :status
                                      )
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < FrontendController
  def index
    @articles = Article.filtered(params)
                        .published
                        .includes(:user)
                        .includes(:category)
                        .page(params[:page])
  end

  def show
    @article = Article.published.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def status_for(article)
    if article.published_at?
      if article.published_at > Time.zone.now
        "Scheduled"
      else
        "Published"
      end
    else
      "Draft"
    end
  end

  def status_label_for(article)
    if article.published_at?
      if article.published_at > Time.zone.now
        content_tag :span, "Scheduled", class: "label label-warning"
      else
        content_tag :span, "Published", class: "label label-success"
      end
    else
      content_tag :span, "Draft", class: "label label-danger"
    end
  end
end

app/views/admin/articles/_form.html.haml
= simple_form_for ["admin", @article] do |f|
  = f.error_notification
  .row
    .col-sm-9
      = f.input :title
      = f.input :excerpt, as: :text, input_html: { class: "form-control", rows: 3 }
    .col-sm-3
      .row
        = f.input :category_id, collection: @categories, prompt: "Select category"
      .row
        = f.input :status, collection: ["Draft", "Published", "Scheduled"], selected: status_for(@article)
        .published-field
          = f.input :published_at, as: :date_time_picker
  .row
    .col-sm-12
      = f.input :body, as: :text, input_html: { class: "form-control", rows: 10 }
  .row
    .col-sm-12
      = f.button :submit, class: "btn btn-primary"

app/views/admin/articles/delete.html.haml
.page-header
  %h1 Delete #{ @article.title }

= simple_form_for ['admin', @article], :method => :delete do |f|
  .alert.alert-warning
    %p 
      #{ icon('warning') } You are about to delete this article.
      Note that this action cannot be undone. 
      Are you sure want to proceed?
  .form-group
    = f.submit 'Yes, Delete it!', class: 'btn btn-danger btn-lg'
    = link_to 'No, I\'ve changed my mind', dashboard_path, class: 'btn btn-success btn-lg'

app/views/admin/articles/edit.html.haml
.page-header
  %h1 Edit #{ @article.title }

= render 'form'

%hr

= link_to 'Back', dashboard_path
\|
= link_to 'Delete', delete_admin_article_path(@article)

app/views/admin/articles/index.html.haml
.page-header
  %h1 Dashboard RailsBlog

%table.table
  %thead
    %tr
      %th #
      %th Title
      %th Category
      %th Date Created
      %th Date Published
      %th Status
      %th
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.id
        %td= link_to article.title, admin_article_path(article)
        %td= article.category.name
        %td= article.created_at.strftime('%d-%m-%Y, %H:%M')
        %td= article.published_at.strftime('%d-%m-%Y, %H:%M') if article.published_at?
        %td= status_label_for(article)
        %td
          = link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_admin_article_path(article), class: 'btn btn-warning btn-xs'
          = link_to '<i class="fa fa-trash"></i> Delete'.html_safe, delete_admin_article_path(article), class: 'btn btn-danger btn-xs'
= paginate @articles

app/views/admin/articles/new.html.haml
.page-header
  %h1 New Article

= render 'form'

%hr

= link_to 'Back', dashboard_path

app/views/admin/articles/show.html.haml
.page-header
  %h1= @article.title
%p.text-muted 
  #{icon('calendar')} Created: #{ @article.created_at.strftime("%d %B %Y at %H:%M") }
  - if @article.published_at?
    &bull;
    Published: #{ @article.published_at.strftime("%d %B %Y at %H:%M")  }
  &bull;
  = status_label_for(@article)

.panel.panel-default
  .panel-heading
    Excerpt
  .panel-body
    %p= @article.excerpt

.panel.panel-default
  .panel-heading
    Body
  .panel-body
    = simple_format @article.body

%hr

= link_to 'Back', dashboard_path
\|
= link_to 'Edit', edit_admin_article_path(@article)
\|
= link_to 'Delete', delete_admin_article_path(@article)