config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /login(.:format)                     devise/sessions#new
#             user_session POST   /login(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /logout(.:format)                    devise/sessions#destroy
#        new_user_password GET    /password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /password/edit(.:format)             devise/passwords#edit
#            user_password PATCH  /password(.:format)                  devise/passwords#update
#                          PUT    /password(.:format)                  devise/passwords#update
#                          POST   /password(.:format)                  devise/passwords#create
# cancel_user_registration GET    /cancel(.:format)                    devise/registrations#cancel
#    new_user_registration GET    /register(.:format)                  devise/registrations#new
#   edit_user_registration GET    /edit(.:format)                      devise/registrations#edit
#        user_registration PATCH  /                                    devise/registrations#update
#                          PUT    /                                    devise/registrations#update
#                          DELETE /                                    devise/registrations#destroy
#                          POST   /                                    devise/registrations#create
#                 articles GET    /articles(.:format)                  articles#index
#                  article GET    /articles/:id(.:format)              articles#show
#     delete_admin_article GET    /admin/articles/:id/delete(.:format) admin/articles#delete
#           admin_articles POST   /admin/articles(.:format)            admin/articles#create
#        new_admin_article GET    /admin/articles/new(.:format)        admin/articles#new
#       edit_admin_article GET    /admin/articles/:id/edit(.:format)   admin/articles#edit
#            admin_article GET    /admin/articles/:id(.:format)        admin/articles#show
#                          PATCH  /admin/articles/:id(.:format)        admin/articles#update
#                          PUT    /admin/articles/:id(.:format)        admin/articles#update
#                          DELETE /admin/articles/:id(.:format)        admin/articles#destroy
#                dashboard GET    /dashboard(.:format)                 admin/articles#index
#                     root GET    /                                    articles#index
# 

Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :articles, only: [:index, :show]

  namespace :admin do
    resources :articles, except: [:index] do
      get :delete, on: :member
    end
  end
  get 'dashboard', to: 'admin/articles#index', as: :dashboard

  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} RailsBlog
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        / %li.active
        /   %a{:href => "#"} Home
        %li
          = link_to '<i class="fa fa-dashboard"></i> My Dashboard'.html_safe, dashboard_path
        %li
          = link_to '<i class="fa fa-pencil"></i> New Article'.html_safe, new_admin_article_path
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to '<i class="fa fa-user-circle"></i> '.html_safe + current_user.fullname, '#'
        %li
          = link_to '<i class="fa fa-power-off"></i> Log Out'.html_safe, destroy_user_session_path, method: :delete

app/views/shared/_blog_nav.html.haml
.blog-masthead
  .container
    %nav.pull-right
      - if user_signed_in?
        = link_to "My Dashboard", dashboard_path, class: "blog-nav-item"
        = link_to "Log Out", destroy_user_session_path, method: :delete, class: "blog-nav-item"
      -else
        = link_to "Sign In", new_user_session_path, class: "blog-nav-item"
        = link_to "Sign Up", new_user_registration_path, class: "blog-nav-item"
    %nav.blog-nav
      = link_to "Home", root_path, class: "blog-nav-item"
      - if @categories.present?
        - @categories.each do |category|
          = link_to category.name, articles_path(category: category.id), class: "blog-nav-item"

app/views/shared/_blog_sidebar.html.haml
.col-sm-3.col-sm-offset-1.blog-sidebar
  .sidebar-module.sidebar-module-inset
    %h4 About
    %p
      Etiam porta
      %em sem malesuada magna
      mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.

  - if @categories.present?
    .sidebar-module.sidebar-module-inset
      %h4 Categories
      %ol.list-unstyled
        %li
          = link_to "All", root_path
        - @categories.each do |category|
          %li
            = link_to "#{ category.name }", articles_path(category: category.id)
  
  - if @archives.present?
    .sidebar-module.sidebar-module-inset
      %h4 Archives
      %ol.list-unstyled
        - @archives.each do |archive|
          %li
            = link_to "#{ archive.month } #{ archive.year } (#{ archive.published })", articles_path(year: archive.year, month: archive.month_num)

app/views/shared/_flash.html.haml
-flash.each do |name, msg|
  = content_tag :div, msg, class: [:alert, alert_for(name)]